/**
 * C++ harness 代码生成器。
 *
 * 给定一个 HarnessSpec（普通函数题），产出一份完整的 harness.cpp，结构：
 *
 *   1) #include <bits/stdc++.h> + using namespace std
 *   2) ListNode / TreeNode struct（按需）
 *   3) #include "solution.cpp"   ← 引入用户代码
 *   4) JSON-ish 反序列化 / 序列化辅助
 *   5) main: 按 spec.params 逐行读 stdin，调用 Solution::funcName，序列化结果到 stdout
 *
 * 输入格式约定（与 leetcode 落盘的 cases/in_<n>.txt 一致）：
 *   每行一个参数的 JSON 字面量，顺序与 params 一致。例如 twoSum：
 *     [2,7,11,15]
 *     9
 *
 * 输出格式：调用结果序列化到 stdout，末尾换行。数组用 [a,b,c]，字符串用 "x"，
 * char 用 'x'，bool 用 true/false，ListNode/TreeNode 用 [v,v,null,...]。
 * 这与题面 expected（meta.json.samples[i].output）的形式一致。
 */

import type { HarnessSpec, HarnessType } from './spec.js';

export interface CppHarnessOptions {
  /**
   * solution 文件名（相对 harness.cpp）。
   * 默认 "solution.cpp"。文本拼接 include，不参与链接。
   */
  solutionFile?: string;
}

/**
 * 生成 C++ harness 源码。spec 必须是 kind=function。
 */
export function generateCppHarness(spec: HarnessSpec, opts: CppHarnessOptions = {}): string {
  if (spec.kind !== 'function') {
    throw new Error(`generateCppHarness 不支持 ${spec.kind}: ${spec.reason}`);
  }
  const solutionFile = opts.solutionFile ?? 'solution.cpp';
  const needList = usesType(spec, 'listnode');
  const needTree = usesType(spec, 'treenode');

  const parts: string[] = [];
  parts.push('// AUTO-GENERATED by oj-agent. 请勿编辑此文件,改 solution.cpp 即可。');
  parts.push('#include <algorithm>');
  parts.push('#include <array>');
  parts.push('#include <bitset>');
  parts.push('#include <cctype>');
  parts.push('#include <climits>');
  parts.push('#include <cmath>');
  parts.push('#include <cstdint>');
  parts.push('#include <cstdio>');
  parts.push('#include <cstdlib>');
  parts.push('#include <cstring>');
  parts.push('#include <deque>');
  parts.push('#include <functional>');
  parts.push('#include <iostream>');
  parts.push('#include <list>');
  parts.push('#include <map>');
  parts.push('#include <memory>');
  parts.push('#include <numeric>');
  parts.push('#include <queue>');
  parts.push('#include <set>');
  parts.push('#include <sstream>');
  parts.push('#include <stack>');
  parts.push('#include <stdexcept>');
  parts.push('#include <string>');
  parts.push('#include <tuple>');
  parts.push('#include <unordered_map>');
  parts.push('#include <unordered_set>');
  parts.push('#include <utility>');
  parts.push('#include <vector>');
  parts.push('using namespace std;');
  parts.push('');
  if (needList) parts.push(LIST_NODE_DEF);
  if (needTree) parts.push(TREE_NODE_DEF);
  if (needList || needTree) parts.push('');
  parts.push(`#include "${solutionFile}"`);
  parts.push('');
  parts.push(READER_RUNTIME);
  parts.push('');
  if (needList) parts.push(LIST_NODE_IO);
  if (needTree) parts.push(TREE_NODE_IO);
  parts.push('');
  parts.push(generateMain(spec));
  return parts.join('\n') + '\n';
}

function generateMain(
  spec: Extract<HarnessSpec, { kind: 'function' }>,
): string {
  const lines: string[] = [];
  lines.push('int main() {');
  lines.push('    std::ios::sync_with_stdio(false);');
  lines.push('    std::string __line;');
  lines.push('    Solution __sol;');
  for (const p of spec.params) {
    lines.push('    if (!std::getline(std::cin, __line)) { std::cerr << "harness: missing input for ' + p.name + '\\n"; return 2; }');
    lines.push(`    ${cppTypeName(p.type)} ${p.name} = __oja_read<${cppTypeName(p.type)}>(__line);`);
  }
  const args = spec.params.map((p) => p.name).join(', ');
  if (spec.returnType.tag === 'void') {
    lines.push(`    __sol.${spec.funcName}(${args});`);
    lines.push('    std::cout << "null\\n";');
  } else {
    lines.push(`    auto __ret = __sol.${spec.funcName}(${args});`);
    lines.push('    __oja_write(std::cout, __ret);');
    lines.push('    std::cout << "\\n";');
  }
  lines.push('    return 0;');
  lines.push('}');
  return lines.join('\n');
}

/** HarnessType → C++ 类型表达式。 */
export function cppTypeName(t: HarnessType): string {
  switch (t.tag) {
    case 'int':
      return 'int';
    case 'long':
      return 'long long';
    case 'double':
      return 'double';
    case 'bool':
      return 'bool';
    case 'string':
      return 'std::string';
    case 'char':
      return 'char';
    case 'void':
      return 'void';
    case 'array':
      return `std::vector<${cppTypeName(t.elem)}>`;
    case 'listnode':
      return 'ListNode*';
    case 'treenode':
      return 'TreeNode*';
  }
}

function usesType(
  spec: Extract<HarnessSpec, { kind: 'function' }>,
  needle: 'listnode' | 'treenode',
): boolean {
  const hit = (t: HarnessType): boolean => {
    if (t.tag === needle) return true;
    if (t.tag === 'array') return hit(t.elem);
    return false;
  };
  if (hit(spec.returnType)) return true;
  for (const p of spec.params) if (hit(p.type)) return true;
  return false;
}

// ====================================================================
// 运行时片段（嵌入到生成代码里的 C++ 源）
// ====================================================================

const LIST_NODE_DEF = `struct ListNode {
    int val;
    ListNode *next;
    ListNode() : val(0), next(nullptr) {}
    ListNode(int x) : val(x), next(nullptr) {}
    ListNode(int x, ListNode *next) : val(x), next(next) {}
};`;

const TREE_NODE_DEF = `struct TreeNode {
    int val;
    TreeNode *left;
    TreeNode *right;
    TreeNode() : val(0), left(nullptr), right(nullptr) {}
    TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
    TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
};`;

/**
 * JSON-ish 字面量解析 / 序列化运行时。
 * 设计目标:
 *   - 单文件、纯标准库、无第三方依赖
 *   - 支持的字面量:
 *       int/long/double:    1   -2   1e9
 *       bool:               true / false
 *       string:             "abc\n\""
 *       char:               "a"     (LeetCode 实际写成长度 1 的字符串)
 *       vector<T>:          [v,v,v]
 *       null:               null    (用于 ListNode / TreeNode 指针反序列化的 nil)
 *   - 不严格校验,够用即可。
 */
const READER_RUNTIME = `// ----- oja harness runtime -----
namespace __oja {
struct R {
    const std::string& s;
    size_t i = 0;
    explicit R(const std::string& str) : s(str) {}
    void skip_ws() { while (i < s.size() && std::isspace((unsigned char)s[i])) ++i; }
    bool eof() { skip_ws(); return i >= s.size(); }
    char peek() { skip_ws(); return i < s.size() ? s[i] : '\\0'; }
    bool accept(char c) { skip_ws(); if (i < s.size() && s[i] == c) { ++i; return true; } return false; }
    void expect(char c) {
        skip_ws();
        if (i >= s.size() || s[i] != c) {
            throw std::runtime_error(std::string("harness: expected '") + c + "' at pos " + std::to_string(i));
        }
        ++i;
    }
    // 读 null,匹配则吞掉,返回 true
    bool try_null() {
        skip_ws();
        if (i + 4 <= s.size() && s.compare(i, 4, "null") == 0) { i += 4; return true; }
        return false;
    }
    long long read_int() {
        skip_ws();
        size_t j = i;
        if (j < s.size() && (s[j] == '-' || s[j] == '+')) ++j;
        while (j < s.size() && std::isdigit((unsigned char)s[j])) ++j;
        if (j == i) throw std::runtime_error("harness: expected int at pos " + std::to_string(i));
        long long v = std::stoll(s.substr(i, j - i));
        i = j;
        return v;
    }
    double read_double() {
        skip_ws();
        size_t j = i;
        if (j < s.size() && (s[j] == '-' || s[j] == '+')) ++j;
        while (j < s.size() && (std::isdigit((unsigned char)s[j]) || s[j] == '.' || s[j] == 'e' || s[j] == 'E' || s[j] == '+' || s[j] == '-')) ++j;
        if (j == i) throw std::runtime_error("harness: expected double at pos " + std::to_string(i));
        double v = std::stod(s.substr(i, j - i));
        i = j;
        return v;
    }
    bool read_bool() {
        skip_ws();
        if (i + 4 <= s.size() && s.compare(i, 4, "true") == 0) { i += 4; return true; }
        if (i + 5 <= s.size() && s.compare(i, 5, "false") == 0) { i += 5; return false; }
        throw std::runtime_error("harness: expected bool at pos " + std::to_string(i));
    }
    std::string read_string() {
        skip_ws();
        expect('"');
        std::string out;
        while (i < s.size() && s[i] != '"') {
            if (s[i] == '\\\\' && i + 1 < s.size()) {
                char c = s[i + 1];
                switch (c) {
                    case 'n': out.push_back('\\n'); break;
                    case 't': out.push_back('\\t'); break;
                    case 'r': out.push_back('\\r'); break;
                    case '\\\\': out.push_back('\\\\'); break;
                    case '"': out.push_back('"'); break;
                    case '/': out.push_back('/'); break;
                    case 'b': out.push_back('\\b'); break;
                    case 'f': out.push_back('\\f'); break;
                    default: out.push_back(c); break;
                }
                i += 2;
            } else {
                out.push_back(s[i]);
                ++i;
            }
        }
        expect('"');
        return out;
    }
};
} // namespace __oja

// 类型分派
template<typename T> T __oja_parse(__oja::R& r);

// 用 SFINAE 让 vector<T> 走 parse_vec
template<typename V> struct __oja_is_vec : std::false_type {};
template<typename T> struct __oja_is_vec<std::vector<T>> : std::true_type { using elem = T; };

template<typename T>
typename std::enable_if<__oja_is_vec<T>::value, T>::type
__oja_parse_dispatch(__oja::R& r);
template<typename T>
typename std::enable_if<!__oja_is_vec<T>::value, T>::type
__oja_parse_dispatch(__oja::R& r) {
    return __oja_parse<T>(r);
}

template<typename T> T __oja_read(const std::string& line) {
    __oja::R r(line);
    return __oja_parse_dispatch<T>(r);
}

template<> inline int __oja_parse<int>(__oja::R& r) { return (int)r.read_int(); }
template<> inline long long __oja_parse<long long>(__oja::R& r) { return r.read_int(); }
template<> inline double __oja_parse<double>(__oja::R& r) { return r.read_double(); }
template<> inline bool __oja_parse<bool>(__oja::R& r) { return r.read_bool(); }
template<> inline std::string __oja_parse<std::string>(__oja::R& r) { return r.read_string(); }
template<> inline char __oja_parse<char>(__oja::R& r) {
    auto s = r.read_string();
    if (s.size() != 1) throw std::runtime_error("harness: expected single char");
    return s[0];
}
template<typename T> std::vector<T> __oja_parse_vec(__oja::R& r) {
    std::vector<T> out;
    r.expect('[');
    r.skip_ws();
    if (r.accept(']')) return out;
    while (true) {
        out.push_back(__oja_parse_dispatch<T>(r));
        if (r.accept(',')) continue;
        r.expect(']');
        break;
    }
    return out;
}

template<typename T>
typename std::enable_if<__oja_is_vec<T>::value, T>::type
__oja_parse_dispatch(__oja::R& r) {
    return __oja_parse_vec<typename __oja_is_vec<T>::elem>(r);
}

// ----- 序列化 -----
inline void __oja_write(std::ostream& os, int v) { os << v; }
inline void __oja_write(std::ostream& os, long long v) { os << v; }
inline void __oja_write(std::ostream& os, double v) {
    // 与 leetcode expected 风格对齐:保留 5 位小数并 trim 尾零
    std::ostringstream ss;
    ss.setf(std::ios::fixed);
    ss.precision(5);
    ss << v;
    std::string s = ss.str();
    if (s.find('.') != std::string::npos) {
        size_t e = s.size();
        while (e > 0 && s[e - 1] == '0') --e;
        if (e > 0 && s[e - 1] == '.') --e;
        s.erase(e);
    }
    os << s;
}
inline void __oja_write(std::ostream& os, bool v) { os << (v ? "true" : "false"); }
inline void __oja_write(std::ostream& os, char c) { os << '"' << c << '"'; }
inline void __oja_write(std::ostream& os, const std::string& s) {
    os << '"';
    for (char c : s) {
        switch (c) {
            case '"': os << "\\\\\\""; break;
            case '\\\\': os << "\\\\\\\\"; break;
            case '\\n': os << "\\\\n"; break;
            case '\\t': os << "\\\\t"; break;
            case '\\r': os << "\\\\r"; break;
            default: os << c; break;
        }
    }
    os << '"';
}
template<typename T>
inline void __oja_write(std::ostream& os, const std::vector<T>& v) {
    os << '[';
    for (size_t i = 0; i < v.size(); ++i) {
        if (i) os << ',';
        __oja_write(os, v[i]);
    }
    os << ']';
}
// ----- end oja harness runtime -----`;

// 在主特化里把 vector<T> 重定向到 parse_vec —— 让用户的 __oja_parse<std::vector<X>>(r) 工作
const LIST_NODE_IO = `// ListNode I/O
inline ListNode* __oja_build_listnode(const std::vector<int>& v) {
    ListNode head(0), *tail = &head;
    for (int x : v) { tail->next = new ListNode(x); tail = tail->next; }
    return head.next;
}
template<> inline ListNode* __oja_parse<ListNode*>(__oja::R& r) {
    if (r.try_null()) return nullptr;
    auto v = __oja_parse_vec<int>(r);
    return __oja_build_listnode(v);
}
inline void __oja_write(std::ostream& os, ListNode* head) {
    os << '[';
    bool first = true;
    while (head) {
        if (!first) os << ',';
        os << head->val;
        first = false;
        head = head->next;
    }
    os << ']';
}`;

const TREE_NODE_IO = `// TreeNode I/O —— leetcode 层序 + null 占位
struct __OjaOptInt { bool has; int val; };
inline std::vector<__OjaOptInt> __oja_parse_optint_vec(__oja::R& r) {
    std::vector<__OjaOptInt> out;
    r.expect('[');
    r.skip_ws();
    if (r.accept(']')) return out;
    while (true) {
        r.skip_ws();
        if (r.try_null()) {
            out.push_back({false, 0});
        } else {
            out.push_back({true, (int)r.read_int()});
        }
        if (r.accept(',')) continue;
        r.expect(']');
        break;
    }
    return out;
}
inline TreeNode* __oja_build_treenode(const std::vector<__OjaOptInt>& v) {
    if (v.empty() || !v[0].has) return nullptr;
    TreeNode* root = new TreeNode(v[0].val);
    std::queue<TreeNode*> q; q.push(root);
    size_t i = 1;
    while (!q.empty() && i < v.size()) {
        TreeNode* cur = q.front(); q.pop();
        if (i < v.size()) {
            if (v[i].has) { cur->left = new TreeNode(v[i].val); q.push(cur->left); }
            ++i;
        }
        if (i < v.size()) {
            if (v[i].has) { cur->right = new TreeNode(v[i].val); q.push(cur->right); }
            ++i;
        }
    }
    return root;
}
template<> inline TreeNode* __oja_parse<TreeNode*>(__oja::R& r) {
    if (r.try_null()) return nullptr;
    auto v = __oja_parse_optint_vec(r);
    return __oja_build_treenode(v);
}
inline void __oja_write(std::ostream& os, TreeNode* root) {
    // 层序输出,trim 末尾连续 null
    os << '[';
    if (!root) { os << ']'; return; }
    std::vector<std::string> tokens;
    std::queue<TreeNode*> q; q.push(root);
    while (!q.empty()) {
        TreeNode* cur = q.front(); q.pop();
        if (!cur) { tokens.push_back("null"); continue; }
        tokens.push_back(std::to_string(cur->val));
        q.push(cur->left);
        q.push(cur->right);
    }
    while (!tokens.empty() && tokens.back() == "null") tokens.pop_back();
    for (size_t i = 0; i < tokens.size(); ++i) { if (i) os << ','; os << tokens[i]; }
    os << ']';
}`;
