/**
 * Java harness 代码生成器。
 *
 * Java 没有 C 风格的文本 include,所以采用双文件 + javac 一起编的方案:
 *   - Solution.java:  来自 leetcode 的裸 class(用户编辑)
 *   - Harness.java:   含 public static void main,内部 new Solution() 调用
 *
 * Java 主类必须 public,所以 Harness 必须叫 Harness.java。LeetCode 的 snippet
 * 不带 public 修饰符,默认包私访问,Harness 与 Solution 在同一默认包中可见。
 *
 * 输入约定与 C++/Python 一致:每行一个参数 JSON 字面量。
 */

import type { HarnessSpec, HarnessType } from './spec.js';

export function generateJavaHarness(spec: HarnessSpec): string {
  if (spec.kind !== 'function') {
    throw new Error(`generateJavaHarness 不支持 ${spec.kind}: ${spec.reason}`);
  }
  const needList = usesType(spec, 'listnode');
  const needTree = usesType(spec, 'treenode');

  const lines: string[] = [];
  lines.push('// AUTO-GENERATED by oj-agent. 请勿编辑此文件,改 Solution.java 即可。');
  lines.push('import java.util.*;');
  lines.push('import java.io.*;');
  lines.push('');
  // Parser 与 Writer 始终引用 ListNode/TreeNode,因此无论题目是否用到,都注入定义。
  // 多一个未使用的 class 不影响编译或行为,但避免了 parser 内符号不全的问题。
  lines.push(JAVA_LIST_NODE);
  lines.push(JAVA_TREE_NODE);
  lines.push('');
  lines.push('public class Harness {');
  lines.push(JAVA_PARSER);
  lines.push(JAVA_WRITER);
  if (needList) lines.push(JAVA_LIST_IO);
  if (needTree) lines.push(JAVA_TREE_IO);
  lines.push('');
  lines.push('    public static void main(String[] args) throws Exception {');
  lines.push('        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));');
  lines.push('        Solution sol = new Solution();');
  for (const p of spec.params) {
    const javaType = javaTypeName(p.type);
    const reader = javaReadCall(p.type);
    lines.push(`        ${javaType} ${p.name} = ${reader};`);
  }
  const args = spec.params.map((p) => p.name).join(', ');
  if (spec.returnType.tag === 'void') {
    lines.push(`        sol.${spec.funcName}(${args});`);
    lines.push('        System.out.println("null");');
  } else {
    const writer = javaWriteCall(spec.returnType, `sol.${spec.funcName}(${args})`);
    lines.push(`        System.out.println(${writer});`);
  }
  lines.push('    }');
  lines.push('}');
  return lines.join('\n') + '\n';
}

/** Java 端的类型表达式。LeetCode Java 题统一用包装类(Integer/Long)还是基本类型？
 *  实际 LeetCode 的 Java snippet 用基本类型 + int[]。我们这边输入用基本类型,
 *  vector 类型用 List<Integer> 还是 int[]？LeetCode 函数签名常见 int[] —— 但 List 更通用
 *  且 boxing 友好。这里:
 *    integer        -> int
 *    long           -> long
 *    double         -> double
 *    bool           -> boolean
 *    string         -> String
 *    char           -> char
 *    integer[]      -> int[]     (与 leetcode 签名一致)
 *    integer[][]    -> int[][]
 *    string[]       -> String[]
 *    char[]         -> char[]
 *    ListNode       -> ListNode
 *    TreeNode       -> TreeNode
 */
export function javaTypeName(t: HarnessType): string {
  switch (t.tag) {
    case 'int': return 'int';
    case 'long': return 'long';
    case 'double': return 'double';
    case 'bool': return 'boolean';
    case 'string': return 'String';
    case 'char': return 'char';
    case 'void': return 'void';
    case 'listnode': return 'ListNode';
    case 'treenode': return 'TreeNode';
    case 'array': {
      const elem = javaTypeName(t.elem);
      return `${elem}[]`;
    }
  }
}

function javaReadCall(t: HarnessType): string {
  switch (t.tag) {
    case 'int': return 'Parser.parseInt(br.readLine())';
    case 'long': return 'Parser.parseLong(br.readLine())';
    case 'double': return 'Parser.parseDouble(br.readLine())';
    case 'bool': return 'Parser.parseBool(br.readLine())';
    case 'string': return 'Parser.parseString(br.readLine())';
    case 'char': return 'Parser.parseChar(br.readLine())';
    case 'listnode': return 'Parser.parseListNode(br.readLine())';
    case 'treenode': return 'Parser.parseTreeNode(br.readLine())';
    case 'array': {
      const elem = t.elem;
      if (elem.tag === 'int') return 'Parser.parseIntArray(br.readLine())';
      if (elem.tag === 'long') return 'Parser.parseLongArray(br.readLine())';
      if (elem.tag === 'double') return 'Parser.parseDoubleArray(br.readLine())';
      if (elem.tag === 'string') return 'Parser.parseStringArray(br.readLine())';
      if (elem.tag === 'char') return 'Parser.parseCharArray(br.readLine())';
      if (elem.tag === 'bool') return 'Parser.parseBoolArray(br.readLine())';
      if (elem.tag === 'array') {
        const inner = elem.elem;
        if (inner.tag === 'int') return 'Parser.parseInt2DArray(br.readLine())';
        if (inner.tag === 'string') return 'Parser.parseString2DArray(br.readLine())';
        if (inner.tag === 'char') return 'Parser.parseChar2DArray(br.readLine())';
      }
      throw new Error(`Java harness: 不支持的数组元素类型 ${JSON.stringify(elem)}`);
    }
    case 'void': throw new Error('参数类型不能是 void');
  }
}

function javaWriteCall(t: HarnessType, expr: string): string {
  switch (t.tag) {
    case 'int':
    case 'long':
      return `String.valueOf(${expr})`;
    case 'double':
      return `Writer.formatDouble(${expr})`;
    case 'bool':
      return `((${expr}) ? "true" : "false")`;
    case 'string':
      return `Writer.quoteString(${expr})`;
    case 'char':
      return `Writer.quoteChar(${expr})`;
    case 'listnode':
      return `Writer.dumpListNode(${expr})`;
    case 'treenode':
      return `Writer.dumpTreeNode(${expr})`;
    case 'array': {
      const elem = t.elem;
      if (elem.tag === 'int') return `Writer.intArray(${expr})`;
      if (elem.tag === 'long') return `Writer.longArray(${expr})`;
      if (elem.tag === 'double') return `Writer.doubleArray(${expr})`;
      if (elem.tag === 'bool') return `Writer.boolArray(${expr})`;
      if (elem.tag === 'string') return `Writer.stringArray(${expr})`;
      if (elem.tag === 'char') return `Writer.charArray(${expr})`;
      if (elem.tag === 'array') {
        const inner = elem.elem;
        if (inner.tag === 'int') return `Writer.int2DArray(${expr})`;
        if (inner.tag === 'string') return `Writer.string2DArray(${expr})`;
        if (inner.tag === 'char') return `Writer.char2DArray(${expr})`;
      }
      throw new Error(`Java harness: 不支持的返回数组类型 ${JSON.stringify(t)}`);
    }
    case 'void': throw new Error('writeCall 不应被 void 调用');
  }
}

function usesType(
  spec: Extract<HarnessSpec, { kind: 'function' }>,
  needle: 'listnode' | 'treenode',
): boolean {
  const hit = (t: HarnessType): boolean => {
    if (t.tag === needle) return true;
    if (t.tag === 'array') return hit(t.elem);
    return false;
  };
  if (hit(spec.returnType)) return true;
  for (const p of spec.params) if (hit(p.type)) return true;
  return false;
}

// ============= 运行时片段 =============

const JAVA_LIST_NODE = `class ListNode {
    int val;
    ListNode next;
    ListNode() {}
    ListNode(int val) { this.val = val; }
    ListNode(int val, ListNode next) { this.val = val; this.next = next; }
}`;

const JAVA_TREE_NODE = `class TreeNode {
    int val;
    TreeNode left;
    TreeNode right;
    TreeNode() {}
    TreeNode(int val) { this.val = val; }
    TreeNode(int val, TreeNode left, TreeNode right) {
        this.val = val; this.left = left; this.right = right;
    }
}`;

/**
 * JSON-ish 解析器。
 * 简化实现:用字符串扫描器,对外暴露 parseInt/parseString/parseIntArray 等静态方法。
 */
const JAVA_PARSER = `    static class Parser {
        String s; int i = 0;
        Parser(String src) { this.s = src == null ? "" : src; }
        void skipWs() { while (i < s.length() && Character.isWhitespace(s.charAt(i))) i++; }
        boolean accept(char c) { skipWs(); if (i < s.length() && s.charAt(i) == c) { i++; return true; } return false; }
        void expect(char c) { skipWs(); if (i >= s.length() || s.charAt(i) != c) throw new RuntimeException("expected " + c + " at " + i); i++; }
        boolean tryNull() { skipWs(); if (i + 4 <= s.length() && s.substring(i, i + 4).equals("null")) { i += 4; return true; } return false; }
        long readLong() {
            skipWs();
            int j = i;
            if (j < s.length() && (s.charAt(j) == '-' || s.charAt(j) == '+')) j++;
            while (j < s.length() && Character.isDigit(s.charAt(j))) j++;
            if (j == i) throw new RuntimeException("expected number");
            long v = Long.parseLong(s.substring(i, j));
            i = j;
            return v;
        }
        double readDouble() {
            skipWs();
            int j = i;
            if (j < s.length() && (s.charAt(j) == '-' || s.charAt(j) == '+')) j++;
            while (j < s.length() && (Character.isDigit(s.charAt(j)) || ".eE+-".indexOf(s.charAt(j)) >= 0)) {
                if ((s.charAt(j) == '+' || s.charAt(j) == '-') && j != i && Character.toLowerCase(s.charAt(j - 1)) != 'e') break;
                j++;
            }
            double v = Double.parseDouble(s.substring(i, j));
            i = j;
            return v;
        }
        boolean readBool() {
            skipWs();
            if (i + 4 <= s.length() && s.substring(i, i + 4).equals("true")) { i += 4; return true; }
            if (i + 5 <= s.length() && s.substring(i, i + 5).equals("false")) { i += 5; return false; }
            throw new RuntimeException("expected bool");
        }
        String readString() {
            skipWs();
            expect('"');
            StringBuilder sb = new StringBuilder();
            while (i < s.length() && s.charAt(i) != '"') {
                char c = s.charAt(i);
                if (c == '\\\\' && i + 1 < s.length()) {
                    char n = s.charAt(i + 1);
                    switch (n) {
                        case 'n': sb.append('\\n'); break;
                        case 't': sb.append('\\t'); break;
                        case 'r': sb.append('\\r'); break;
                        case '"': sb.append('"'); break;
                        case '\\\\': sb.append('\\\\'); break;
                        case '/': sb.append('/'); break;
                        default: sb.append(n); break;
                    }
                    i += 2;
                } else {
                    sb.append(c); i++;
                }
            }
            expect('"');
            return sb.toString();
        }
        static int parseInt(String line) { Parser p = new Parser(line); return (int) p.readLong(); }
        static long parseLong(String line) { return new Parser(line).readLong(); }
        static double parseDouble(String line) { return new Parser(line).readDouble(); }
        static boolean parseBool(String line) { return new Parser(line).readBool(); }
        static String parseString(String line) { return new Parser(line).readString(); }
        static char parseChar(String line) {
            String s = new Parser(line).readString();
            if (s.length() != 1) throw new RuntimeException("expected single char");
            return s.charAt(0);
        }
        static int[] parseIntArray(String line) {
            Parser p = new Parser(line); p.expect('['); java.util.ArrayList<Integer> a = new java.util.ArrayList<>();
            p.skipWs(); if (p.accept(']')) return new int[0];
            while (true) { a.add((int) p.readLong()); if (p.accept(',')) continue; p.expect(']'); break; }
            int[] r = new int[a.size()]; for (int k = 0; k < a.size(); k++) r[k] = a.get(k); return r;
        }
        static long[] parseLongArray(String line) {
            Parser p = new Parser(line); p.expect('['); java.util.ArrayList<Long> a = new java.util.ArrayList<>();
            p.skipWs(); if (p.accept(']')) return new long[0];
            while (true) { a.add(p.readLong()); if (p.accept(',')) continue; p.expect(']'); break; }
            long[] r = new long[a.size()]; for (int k = 0; k < a.size(); k++) r[k] = a.get(k); return r;
        }
        static double[] parseDoubleArray(String line) {
            Parser p = new Parser(line); p.expect('['); java.util.ArrayList<Double> a = new java.util.ArrayList<>();
            p.skipWs(); if (p.accept(']')) return new double[0];
            while (true) { a.add(p.readDouble()); if (p.accept(',')) continue; p.expect(']'); break; }
            double[] r = new double[a.size()]; for (int k = 0; k < a.size(); k++) r[k] = a.get(k); return r;
        }
        static String[] parseStringArray(String line) {
            Parser p = new Parser(line); p.expect('['); java.util.ArrayList<String> a = new java.util.ArrayList<>();
            p.skipWs(); if (p.accept(']')) return new String[0];
            while (true) { a.add(p.readString()); if (p.accept(',')) continue; p.expect(']'); break; }
            return a.toArray(new String[0]);
        }
        static char[] parseCharArray(String line) {
            String[] arr = parseStringArray(line);
            char[] r = new char[arr.length];
            for (int k = 0; k < arr.length; k++) { if (arr[k].length() != 1) throw new RuntimeException("char[] elem must be 1 char"); r[k] = arr[k].charAt(0); }
            return r;
        }
        static boolean[] parseBoolArray(String line) {
            Parser p = new Parser(line); p.expect('['); java.util.ArrayList<Boolean> a = new java.util.ArrayList<>();
            p.skipWs(); if (p.accept(']')) return new boolean[0];
            while (true) { a.add(p.readBool()); if (p.accept(',')) continue; p.expect(']'); break; }
            boolean[] r = new boolean[a.size()]; for (int k = 0; k < a.size(); k++) r[k] = a.get(k); return r;
        }
        static int[][] parseInt2DArray(String line) {
            Parser p = new Parser(line); p.expect('['); java.util.ArrayList<int[]> a = new java.util.ArrayList<>();
            p.skipWs(); if (p.accept(']')) return new int[0][];
            while (true) {
                p.expect('['); java.util.ArrayList<Integer> row = new java.util.ArrayList<>();
                p.skipWs();
                if (!p.accept(']')) {
                    while (true) { row.add((int) p.readLong()); if (p.accept(',')) continue; p.expect(']'); break; }
                }
                int[] r = new int[row.size()]; for (int k = 0; k < row.size(); k++) r[k] = row.get(k); a.add(r);
                if (p.accept(',')) continue; p.expect(']'); break;
            }
            return a.toArray(new int[0][]);
        }
        static String[][] parseString2DArray(String line) {
            Parser p = new Parser(line); p.expect('['); java.util.ArrayList<String[]> a = new java.util.ArrayList<>();
            p.skipWs(); if (p.accept(']')) return new String[0][];
            while (true) {
                p.expect('['); java.util.ArrayList<String> row = new java.util.ArrayList<>();
                p.skipWs();
                if (!p.accept(']')) {
                    while (true) { row.add(p.readString()); if (p.accept(',')) continue; p.expect(']'); break; }
                }
                a.add(row.toArray(new String[0]));
                if (p.accept(',')) continue; p.expect(']'); break;
            }
            return a.toArray(new String[0][]);
        }
        static char[][] parseChar2DArray(String line) {
            String[][] s = parseString2DArray(line);
            char[][] r = new char[s.length][];
            for (int i = 0; i < s.length; i++) {
                r[i] = new char[s[i].length];
                for (int j = 0; j < s[i].length; j++) {
                    if (s[i][j].length() != 1) throw new RuntimeException("char[][] elem must be 1 char");
                    r[i][j] = s[i][j].charAt(0);
                }
            }
            return r;
        }
        static ListNode parseListNode(String line) {
            Parser p = new Parser(line);
            if (p.tryNull()) return null;
            int[] arr = parseIntArray(line);
            ListNode head = new ListNode(0), tail = head;
            for (int v : arr) { tail.next = new ListNode(v); tail = tail.next; }
            return head.next;
        }
        static TreeNode parseTreeNode(String line) {
            Parser p = new Parser(line);
            if (p.tryNull()) return null;
            // 解析为 Integer[],其中 null 用 Integer 包装的 null 表示
            p.expect('[');
            java.util.ArrayList<Integer> a = new java.util.ArrayList<>();
            p.skipWs();
            if (p.accept(']')) return null;
            while (true) {
                p.skipWs();
                if (p.tryNull()) a.add(null);
                else a.add((int) p.readLong());
                if (p.accept(',')) continue;
                p.expect(']');
                break;
            }
            if (a.isEmpty() || a.get(0) == null) return null;
            TreeNode root = new TreeNode(a.get(0));
            java.util.ArrayDeque<TreeNode> q = new java.util.ArrayDeque<>();
            q.add(root);
            int i = 1;
            while (!q.isEmpty() && i < a.size()) {
                TreeNode cur = q.poll();
                if (i < a.size()) {
                    Integer v = a.get(i++);
                    if (v != null) { cur.left = new TreeNode(v); q.add(cur.left); }
                }
                if (i < a.size()) {
                    Integer v = a.get(i++);
                    if (v != null) { cur.right = new TreeNode(v); q.add(cur.right); }
                }
            }
            return root;
        }
    }`;

const JAVA_WRITER = `    static class Writer {
        static String quoteString(String s) {
            StringBuilder sb = new StringBuilder("\\"");
            for (int i = 0; i < s.length(); i++) {
                char c = s.charAt(i);
                switch (c) {
                    case '"': sb.append("\\\\\\""); break;
                    case '\\\\': sb.append("\\\\\\\\"); break;
                    case '\\n': sb.append("\\\\n"); break;
                    case '\\t': sb.append("\\\\t"); break;
                    case '\\r': sb.append("\\\\r"); break;
                    default: sb.append(c); break;
                }
            }
            sb.append('"');
            return sb.toString();
        }
        static String quoteChar(char c) { return quoteString(String.valueOf(c)); }
        static String formatDouble(double v) {
            String s = String.format(java.util.Locale.ROOT, "%.5f", v);
            int end = s.length();
            while (end > 0 && s.charAt(end - 1) == '0') end--;
            if (end > 0 && s.charAt(end - 1) == '.') end--;
            String r = s.substring(0, end);
            return r.isEmpty() ? "0" : r;
        }
        static String intArray(int[] a) {
            StringBuilder sb = new StringBuilder("[");
            for (int i = 0; i < a.length; i++) { if (i > 0) sb.append(','); sb.append(a[i]); }
            sb.append(']'); return sb.toString();
        }
        static String longArray(long[] a) {
            StringBuilder sb = new StringBuilder("[");
            for (int i = 0; i < a.length; i++) { if (i > 0) sb.append(','); sb.append(a[i]); }
            sb.append(']'); return sb.toString();
        }
        static String doubleArray(double[] a) {
            StringBuilder sb = new StringBuilder("[");
            for (int i = 0; i < a.length; i++) { if (i > 0) sb.append(','); sb.append(formatDouble(a[i])); }
            sb.append(']'); return sb.toString();
        }
        static String boolArray(boolean[] a) {
            StringBuilder sb = new StringBuilder("[");
            for (int i = 0; i < a.length; i++) { if (i > 0) sb.append(','); sb.append(a[i] ? "true" : "false"); }
            sb.append(']'); return sb.toString();
        }
        static String stringArray(String[] a) {
            StringBuilder sb = new StringBuilder("[");
            for (int i = 0; i < a.length; i++) { if (i > 0) sb.append(','); sb.append(quoteString(a[i])); }
            sb.append(']'); return sb.toString();
        }
        static String charArray(char[] a) {
            StringBuilder sb = new StringBuilder("[");
            for (int i = 0; i < a.length; i++) { if (i > 0) sb.append(','); sb.append(quoteChar(a[i])); }
            sb.append(']'); return sb.toString();
        }
        static String int2DArray(int[][] a) {
            StringBuilder sb = new StringBuilder("[");
            for (int i = 0; i < a.length; i++) { if (i > 0) sb.append(','); sb.append(intArray(a[i])); }
            sb.append(']'); return sb.toString();
        }
        static String string2DArray(String[][] a) {
            StringBuilder sb = new StringBuilder("[");
            for (int i = 0; i < a.length; i++) { if (i > 0) sb.append(','); sb.append(stringArray(a[i])); }
            sb.append(']'); return sb.toString();
        }
        static String char2DArray(char[][] a) {
            StringBuilder sb = new StringBuilder("[");
            for (int i = 0; i < a.length; i++) { if (i > 0) sb.append(','); sb.append(charArray(a[i])); }
            sb.append(']'); return sb.toString();
        }
        static String dumpListNode(ListNode head) {
            StringBuilder sb = new StringBuilder("[");
            boolean first = true;
            while (head != null) {
                if (!first) sb.append(',');
                sb.append(head.val);
                first = false;
                head = head.next;
            }
            sb.append(']');
            return sb.toString();
        }
        static String dumpTreeNode(TreeNode root) {
            if (root == null) return "[]";
            java.util.ArrayList<String> tokens = new java.util.ArrayList<>();
            // ArrayDeque 不接受 null,用 LinkedList 容忍 null 占位
            java.util.LinkedList<TreeNode> q = new java.util.LinkedList<>();
            q.add(root);
            while (!q.isEmpty()) {
                TreeNode cur = q.poll();
                if (cur == null) { tokens.add("null"); continue; }
                tokens.add(String.valueOf(cur.val));
                q.add(cur.left);
                q.add(cur.right);
            }
            while (!tokens.isEmpty() && tokens.get(tokens.size() - 1).equals("null")) tokens.remove(tokens.size() - 1);
            StringBuilder sb = new StringBuilder("[");
            for (int i = 0; i < tokens.size(); i++) { if (i > 0) sb.append(','); sb.append(tokens.get(i)); }
            sb.append(']');
            return sb.toString();
        }
    }`;

const JAVA_LIST_IO = '';

const JAVA_TREE_IO = '';
