/**
 * JavaScript harness 代码生成器。
 *
 * 难点:leetcode 给的 JS snippet 是裸函数 `var twoSum = function(...) {}`,
 * 既无 module.exports 也无 ES Module 导出。
 *
 * 方案:harness.js 用 node:vm 在新上下文里 require('fs') 读取 solution.js,
 * runInContext 执行,从 context 取出全局函数变量。这样 solution.js 保持
 * leetcode 网页上的原始形式不动。
 *
 * 输入约定与 C++/Python 一致:每行一个参数 JSON 字面量。
 */

import type { HarnessSpec, HarnessType } from './spec.js';

export function generateJsHarness(spec: HarnessSpec): string {
  if (spec.kind !== 'function') {
    throw new Error(`generateJsHarness 不支持 ${spec.kind}: ${spec.reason}`);
  }
  const needList = usesType(spec, 'listnode');
  const needTree = usesType(spec, 'treenode');

  const lines: string[] = [];
  lines.push('// AUTO-GENERATED by oj-agent. 请勿编辑此文件,改 solution.js 即可。');
  lines.push("'use strict';");
  lines.push("const fs = require('node:fs');");
  lines.push("const path = require('node:path');");
  lines.push("const vm = require('node:vm');");
  lines.push('');
  if (needList) lines.push(JS_LIST_NODE);
  if (needTree) lines.push(JS_TREE_NODE);
  if (needList || needTree) lines.push('');
  lines.push(JS_HELPERS);
  lines.push('');
  // 在专用 vm context 中执行 solution.js,把 ListNode/TreeNode 注入到该上下文,取出函数
  lines.push("const __solSrc = fs.readFileSync(path.join(__dirname, 'solution.js'), 'utf-8');");
  lines.push('const __ctx = {};');
  if (needList) lines.push('__ctx.ListNode = ListNode;');
  if (needTree) lines.push('__ctx.TreeNode = TreeNode;');
  lines.push('vm.createContext(__ctx);');
  lines.push("vm.runInContext(__solSrc, __ctx, { filename: 'solution.js' });");
  lines.push(`const __fn = __ctx[${JSON.stringify(spec.funcName)}];`);
  lines.push(`if (typeof __fn !== 'function') {`);
  lines.push(`  console.error('harness: 未在 solution.js 中找到函数 ${spec.funcName}');`);
  lines.push('  process.exit(2);');
  lines.push('}');
  lines.push('');
  lines.push("const __input = fs.readFileSync(0, 'utf-8');");
  lines.push("const __lines = __input.split('\\n');");
  lines.push('');
  for (let i = 0; i < spec.params.length; i++) {
    const p = spec.params[i]!;
    lines.push(`const ${p.name} = __deserialize(JSON.parse(__lines[${i}] ?? 'null'), ${jsTypeTag(p.type)});`);
  }
  const args = spec.params.map((p) => p.name).join(', ');
  if (spec.returnType.tag === 'void') {
    lines.push(`__fn(${args});`);
    lines.push('process.stdout.write("null\\n");');
  } else {
    lines.push(`const __ret = __fn(${args});`);
    lines.push(`process.stdout.write(__serialize(__ret, ${jsTypeTag(spec.returnType)}) + "\\n");`);
  }
  return lines.join('\n') + '\n';
}

function jsTypeTag(t: HarnessType): string {
  return JSON.stringify(t);
}

function usesType(
  spec: Extract<HarnessSpec, { kind: 'function' }>,
  needle: 'listnode' | 'treenode',
): boolean {
  const hit = (t: HarnessType): boolean => {
    if (t.tag === needle) return true;
    if (t.tag === 'array') return hit(t.elem);
    return false;
  };
  if (hit(spec.returnType)) return true;
  for (const p of spec.params) if (hit(p.type)) return true;
  return false;
}

// ============= 运行时片段 =============

const JS_LIST_NODE = `function ListNode(val, next) {
  this.val = (val === undefined ? 0 : val);
  this.next = (next === undefined ? null : next);
}`;

const JS_TREE_NODE = `function TreeNode(val, left, right) {
  this.val = (val === undefined ? 0 : val);
  this.left = (left === undefined ? null : left);
  this.right = (right === undefined ? null : right);
}`;

const JS_HELPERS = `function __buildListNode(arr) {
  if (!Array.isArray(arr)) return null;
  let head = { next: null };
  let tail = head;
  for (const v of arr) {
    tail.next = new ListNode(v);
    tail = tail.next;
  }
  return head.next;
}

function __dumpListNode(node) {
  const out = [];
  while (node) { out.push(node.val); node = node.next; }
  return out;
}

function __buildTreeNode(arr) {
  if (!Array.isArray(arr) || arr.length === 0 || arr[0] === null || arr[0] === undefined) return null;
  const root = new TreeNode(arr[0]);
  const queue = [root];
  let i = 1;
  while (queue.length && i < arr.length) {
    const cur = queue.shift();
    if (i < arr.length) {
      const v = arr[i++];
      if (v !== null && v !== undefined) { cur.left = new TreeNode(v); queue.push(cur.left); }
    }
    if (i < arr.length) {
      const v = arr[i++];
      if (v !== null && v !== undefined) { cur.right = new TreeNode(v); queue.push(cur.right); }
    }
  }
  return root;
}

function __dumpTreeNode(root) {
  if (!root) return [];
  const out = [];
  const q = [root];
  while (q.length) {
    const cur = q.shift();
    if (cur === null) { out.push(null); continue; }
    out.push(cur.val);
    q.push(cur.left ?? null);
    q.push(cur.right ?? null);
  }
  while (out.length && out[out.length - 1] === null) out.pop();
  return out;
}

function __deserialize(value, type_tag) {
  if (!type_tag) return value;
  const tag = type_tag.tag;
  if (tag === 'listnode') return value === null ? null : __buildListNode(value);
  if (tag === 'treenode') return value === null ? null : __buildTreeNode(value);
  if (tag === 'array') return (value ?? []).map(v => __deserialize(v, type_tag.elem));
  return value;
}

function __formatNum(v) {
  if (Number.isInteger(v)) return String(v);
  // 与 C++/Python 对齐:5 位小数 trim 尾零
  let s = v.toFixed(5);
  s = s.replace(/0+$/, '').replace(/\\.$/, '');
  return s || '0';
}

function __serialize(value, type_tag) {
  if (type_tag) {
    const tag = type_tag.tag;
    if (tag === 'listnode') return __serialize(__dumpListNode(value), { tag: 'array', elem: { tag: 'int' } });
    if (tag === 'treenode') {
      const arr = __dumpTreeNode(value);
      return '[' + arr.map(v => v === null ? 'null' : String(v)).join(',') + ']';
    }
    if (tag === 'array') return '[' + (value ?? []).map(v => __serialize(v, type_tag.elem)).join(',') + ']';
    if (tag === 'bool') return value ? 'true' : 'false';
    if (tag === 'string' || tag === 'char') return JSON.stringify(value);
    if (tag === 'double') return __formatNum(value);
    return String(value); // int / long
  }
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') return __formatNum(value);
  if (typeof value === 'string') return JSON.stringify(value);
  if (Array.isArray(value)) return '[' + value.map(v => __serialize(v, null)).join(',') + ']';
  if (value === null || value === undefined) return 'null';
  return JSON.stringify(value);
}`;
