/**
 * Python3 harness 代码生成器。
 *
 * 产出的 harness.py 结构:
 *   1) import sys, json, collections
 *   2) ListNode / TreeNode 类定义(按需)
 *   3) from solution import Solution     ← 引入用户代码
 *   4) JSON 字面量反序列化(直接用 json.loads,leetcode 字面量本身就是合法 JSON)
 *   5) 输出序列化(数组/链表/树/字符串/bool/数字 均序列化为 leetcode 形式)
 *   6) __main__: 按 spec.params 逐行 sys.stdin.readline 读取,调用,输出
 *
 * Python 不需要文本 include 之类的把戏 —— 直接 import 就行。
 */

import type { HarnessSpec, HarnessType } from './spec.js';

export function generatePythonHarness(spec: HarnessSpec): string {
  if (spec.kind !== 'function') {
    throw new Error(`generatePythonHarness 不支持 ${spec.kind}: ${spec.reason}`);
  }
  const needList = usesType(spec, 'listnode');
  const needTree = usesType(spec, 'treenode');

  const lines: string[] = [];
  lines.push('# AUTO-GENERATED by oj-agent. 请勿编辑此文件,改 solution.py 即可。');
  lines.push('import sys');
  lines.push('import json');
  lines.push('from typing import List, Optional');
  lines.push('');
  if (needList) lines.push(PY_LIST_NODE);
  if (needTree) lines.push(PY_TREE_NODE);
  if (needList || needTree) lines.push('');
  lines.push('from solution import Solution');
  lines.push('');
  if (needList) lines.push(PY_LIST_NODE_IO);
  if (needTree) lines.push(PY_TREE_NODE_IO);
  lines.push(PY_SERIALIZE);
  lines.push('');
  lines.push('def _read_arg(line, type_tag):');
  lines.push('    return _deserialize(json.loads(line), type_tag)');
  lines.push('');
  lines.push('def _deserialize(value, type_tag):');
  lines.push('    if type_tag is None: return value');
  lines.push('    tag = type_tag["tag"]');
  lines.push('    if tag == "listnode": return _build_listnode(value) if value is not None else None');
  lines.push('    if tag == "treenode": return _build_treenode(value) if value is not None else None');
  lines.push('    if tag == "array":');
  lines.push('        elem = type_tag["elem"]');
  lines.push('        return [_deserialize(v, elem) for v in (value or [])]');
  lines.push('    return value  # int/long/double/bool/string/char 原样');
  lines.push('');
  lines.push('if __name__ == "__main__":');
  lines.push('    _sol = Solution()');
  for (const p of spec.params) {
    lines.push(`    _line = sys.stdin.readline()`);
    lines.push(`    ${p.name} = _read_arg(_line, ${pyTypeTag(p.type)})`);
  }
  const args = spec.params.map((p) => p.name).join(', ');
  if (spec.returnType.tag === 'void') {
    lines.push(`    _sol.${spec.funcName}(${args})`);
    lines.push('    sys.stdout.write("null\\n")');
  } else {
    lines.push(`    _ret = _sol.${spec.funcName}(${args})`);
    lines.push(`    sys.stdout.write(_serialize(_ret, ${pyTypeTag(spec.returnType)}) + "\\n")`);
  }
  return lines.join('\n') + '\n';
}

/** 把 HarnessType 转成 Python 端可读的 JSON 字符串(作为运行时元数据)。 */
function pyTypeTag(t: HarnessType): string {
  return JSON.stringify(t);
}

function usesType(
  spec: Extract<HarnessSpec, { kind: 'function' }>,
  needle: 'listnode' | 'treenode',
): boolean {
  const hit = (t: HarnessType): boolean => {
    if (t.tag === needle) return true;
    if (t.tag === 'array') return hit(t.elem);
    return false;
  };
  if (hit(spec.returnType)) return true;
  for (const p of spec.params) if (hit(p.type)) return true;
  return false;
}

// ============= 运行时片段 =============

const PY_LIST_NODE = `class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next`;

const PY_TREE_NODE = `class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right`;

const PY_LIST_NODE_IO = `def _build_listnode(arr):
    head = ListNode(0)
    tail = head
    for v in arr:
        tail.next = ListNode(v)
        tail = tail.next
    return head.next

def _dump_listnode(node):
    out = []
    while node is not None:
        out.append(node.val)
        node = node.next
    return out
`;

const PY_TREE_NODE_IO = `def _build_treenode(arr):
    if not arr or arr[0] is None: return None
    from collections import deque
    root = TreeNode(arr[0])
    q = deque([root])
    i = 1
    while q and i < len(arr):
        cur = q.popleft()
        if i < len(arr):
            v = arr[i]; i += 1
            if v is not None:
                cur.left = TreeNode(v); q.append(cur.left)
        if i < len(arr):
            v = arr[i]; i += 1
            if v is not None:
                cur.right = TreeNode(v); q.append(cur.right)
    return root

def _dump_treenode(root):
    if root is None: return []
    from collections import deque
    out = []
    q = deque([root])
    while q:
        cur = q.popleft()
        if cur is None:
            out.append(None)
            continue
        out.append(cur.val)
        q.append(cur.left)
        q.append(cur.right)
    while out and out[-1] is None:
        out.pop()
    return out
`;

/**
 * _serialize: 把返回值序列化为与 leetcode expected 一致的字符串(无空格 JSON)。
 * 关键点:
 *   - python 的 True/False 要小写; bool 也是 int 子类,先判 bool 再判 int
 *   - 数字直接 str
 *   - 数组递归
 *   - ListNode/TreeNode 先 dump 成数组
 */
const PY_SERIALIZE = `def _serialize(value, type_tag):
    if type_tag is not None:
        tag = type_tag["tag"]
        if tag == "listnode":
            return _serialize(_dump_listnode(value), {"tag": "array", "elem": {"tag": "int"}})
        if tag == "treenode":
            arr = _dump_treenode(value)
            parts = []
            for v in arr:
                parts.append("null" if v is None else str(v))
            return "[" + ",".join(parts) + "]"
        if tag == "array":
            elem = type_tag["elem"]
            return "[" + ",".join(_serialize(v, elem) for v in (value or [])) + "]"
        if tag == "bool":
            return "true" if value else "false"
        if tag == "string" or tag == "char":
            return json.dumps(value, ensure_ascii=False)
        if tag == "double":
            # 5 位小数,trim 尾零(与 C++ 保持一致)
            s = f"{value:.5f}".rstrip("0").rstrip(".")
            return s if s else "0"
        # int / long
        return str(value)
    # 兜底:自动判别
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int,)):
        return str(value)
    if isinstance(value, float):
        s = f"{value:.5f}".rstrip("0").rstrip(".")
        return s if s else "0"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list):
        return "[" + ",".join(_serialize(v, None) for v in value) + "]"
    return json.dumps(value, ensure_ascii=False)
`;
